import { isCanonicalSemester, isCanonicalYearLevel, normalizeSemester, normalizeYearLevel } from '../normalizeCurriculum';
import { mergeHeaderRows, looksLikeSubHeaderRow, looksLikeTableHeaderRow, scoreHeaderCells } from './columnMap';
import {
  FIELD_LABELS,
  type ColumnMapping,
  type ImportDiagnostic,
  type ParseWorkbookResult,
  type ParsedSubjectRow,
  type SheetInput,
  type WorkbookInput,
} from './types';
import { detectYearSemester, detectYearSemesterFromSheetName, isSectionHeadingRow, looksLikeCourseCode } from './yearSemester';

const SKIP_LABELS = /^(total|grand total|subtotal|summary|notes|remarks|curriculum|old curriculum|new curriculum|republic of the philippines|north eastern mindanao state university|evaluated by|generated by)\b/i;

export function applyMerges(rows: unknown[][], merges?: Array<{ s: { r: number; c: number }; e: { r: number; c: number } }>): unknown[][] {
  if (!merges?.length) return rows;
  const copy = rows.map(row => [...row]);
  for (const merge of merges) {
    const value = copy[merge.s.r]?.[merge.s.c];
    for (let r = merge.s.r; r <= merge.e.r; r++) {
      if (!copy[r]) copy[r] = [];
      for (let c = merge.s.c; c <= merge.e.c; c++) {
        const current = copy[r][c];
        if (current === '' || current == null) copy[r][c] = value;
      }
    }
  }
  return copy;
}

export function cellStr(raw: unknown[]): string[] {
  return raw.map(c => String(c ?? '').replace(/\u00a0/g, ' ').trim());
}

export function parseNum(v: unknown): number {
  const s = String(v ?? '').replace(/[^0-9.]/g, '');
  const n = parseFloat(s);
  return Number.isFinite(n) ? n : 0;
}

function isEmptyRow(cells: string[]): boolean {
  return cells.every(c => !c);
}

function isNoiseRow(cells: string[]): boolean {
  const nonEmpty = cells.filter(Boolean);
  if (nonEmpty.length === 0) return true;
  const joined = nonEmpty.join(' ').trim();
  if (SKIP_LABELS.test(joined)) return true;
  if (nonEmpty.length === 1 && SKIP_LABELS.test(nonEmpty[0])) return true;
  if (nonEmpty.some(c => SKIP_LABELS.test(c)) && !nonEmpty.some(c => looksLikeCourseCode(c))) {
    const first = nonEmpty[0].toUpperCase();
    if (SKIP_LABELS.test(first) || nonEmpty.some(c => /^total$/i.test(c))) return true;
  }
  return false;
}

function isLikelySubject(code: string, title: string): boolean {
  if (!code || !title) return false;
  if (SKIP_LABELS.test(code) || SKIP_LABELS.test(title)) return false;
  if (code.length > 40 || title.length > 255) return false;
  const codeLooksValid = looksLikeCourseCode(code) || (code.length <= 24 && /[A-Za-z]/.test(code));
  const titleLooksValid = title.length >= 3 && /[A-Za-z]/.test(title);
  return codeLooksValid && titleLooksValid;
}

function findBestHeader(rows: string[][]): { index: number; mappings: ColumnMapping[]; score: number } | null {
  let best: { index: number; mappings: ColumnMapping[]; score: number } | null = null;
  for (let i = 0; i < rows.length; i++) {
    const single = scoreHeaderCells(rows[i]);
    let score = single.score;
    let mappings = single.mappings;
    if (i + 1 < rows.length && looksLikeSubHeaderRow(rows[i + 1])) {
      const merged = scoreHeaderCells(mergeHeaderRows(rows[i], rows[i + 1]));
      if (merged.score > score) {
        score = merged.score;
        mappings = merged.mappings;
      }
    }
    if (!best || score > best.score) best = { index: i, mappings, score };
  }
  if (!best || best.score < 3) return null;
  const hasCode = best.mappings.some(m => m.field === 'courseCode' && m.confidence >= 72);
  const hasTitle = best.mappings.some(m => m.field === 'descriptiveTitle' && m.confidence >= 80);
  if (!hasCode || !hasTitle) return null;
  return best;
}

function sheetHasCurriculumSignal(rows: string[][]): number {
  const header = findBestHeader(rows);
  if (!header) return 0;
  let subjects = 0;
  for (let i = header.index + 1; i < rows.length; i++) {
    if (isSectionHeadingRow(rows[i]) || isEmptyRow(rows[i]) || isNoiseRow(rows[i])) continue;
    const code = col(rows[i], header.mappings, 'courseCode');
    const title = col(rows[i], header.mappings, 'descriptiveTitle');
    if (code && title) subjects++;
  }
  return header.score * 10 + subjects;
}

function col(cells: string[], mappings: ColumnMapping[], field: ColumnMapping['field']): string {
  const mapping = mappings.find(m => m.field === field);
  if (!mapping) return '';
  return cells[mapping.columnIndex] ?? '';
}

function parseSheet(
  sheet: SheetInput,
  fallbackYearSem: { yearLevel: string; semester: string } | null,
): { rows: ParsedSubjectRow[]; header: ReturnType<typeof findBestHeader>; inspected: number } {
  const raw = applyMerges(sheet.rows, sheet.merges);
  const rows = raw.map(r => cellStr(Array.isArray(r) ? r : []));
  const header = findBestHeader(rows);
  if (!header) return { rows: [], header: null, inspected: rows.length };

  const map = Object.fromEntries(header.mappings.map(m => [m.field, m.columnIndex])) as Partial<Record<ColumnMapping['field'], number>>;
  let yearLevel = fallbackYearSem?.yearLevel ?? '';
  let semester = fallbackYearSem?.semester ?? '';
  const parsed: ParsedSubjectRow[] = [];

  for (let i = 0; i < rows.length; i++) {
    if (i === header.index) continue;
    if (i === header.index + 1 && looksLikeSubHeaderRow(rows[i])) continue;
    const cells = rows[i];
    if (isEmptyRow(cells)) continue;

    if (isSectionHeadingRow(cells)) {
      const section = detectYearSemester(cells);
      if (section) {
        yearLevel = section.yearLevel;
        semester = section.semester;
      }
      continue;
    }
    if (looksLikeTableHeaderRow(cells) || looksLikeSubHeaderRow(cells)) continue;
    if (isNoiseRow(cells)) continue;

    const subjectCode = String(map.courseCode != null ? cells[map.courseCode] ?? '' : '').toUpperCase().replace(/\s+/g, ' ').trim();
    const subjectName = String(map.descriptiveTitle != null ? cells[map.descriptiveTitle] ?? '' : '').replace(/\s+/g, ' ').trim();
    const lectureHours = parseNum(map.lectureHours != null ? cells[map.lectureHours] : '');
    const laboratoryHours = parseNum(map.labHours != null ? cells[map.labHours] : '');
    const creditUnits = parseNum(map.creditUnits != null ? cells[map.creditUnits] : '');
    const prerequisites = String(map.prerequisites != null ? cells[map.prerequisites] ?? '' : '').trim();
    const grade = String(map.grade != null ? cells[map.grade] ?? '' : '').trim();
    const yearFromCol = String(map.yearLevel != null ? cells[map.yearLevel] ?? '' : '');
    const semFromCol = String(map.semester != null ? cells[map.semester] ?? '' : '');
    const yearSemFromCol = String(map.yearSemester != null ? cells[map.yearSemester] ?? '' : '');

    if (!isLikelySubject(subjectCode, subjectName)) continue;

    const fromCombined = detectYearSemester([yearSemFromCol]);
    const normalizedYearCol = normalizeYearLevel(yearFromCol);
    const normalizedSemCol = normalizeSemester(semFromCol);
    const rowYear = fromCombined?.yearLevel
      ?? (isCanonicalYearLevel(normalizedYearCol)
        ? normalizedYearCol
        : (detectYearSemester([yearFromCol])?.yearLevel ?? yearLevel));
    const rowSem = fromCombined?.semester
      ?? (isCanonicalSemester(normalizedSemCol)
        ? normalizedSemCol
        : (detectYearSemester([semFromCol])?.semester ?? semester));

    const errors: string[] = [];
    if (!rowYear || !rowSem) errors.push('Year level / semester not detected');
    if (map.creditUnits == null) errors.push('Credit Units column was not mapped');
    if (creditUnits < 0) errors.push('Credit Units cannot be negative');
    if (subjectCode.length > 50) errors.push('Course Code exceeds 50 characters');
    if (subjectName.length > 255) errors.push('Descriptive Title exceeds 255 characters');

    parsed.push({
      rowNum: i + 1,
      sheetName: sheet.name,
      yearLevel: rowYear,
      semester: rowSem,
      subjectCode,
      subjectName,
      lectureHours,
      laboratoryHours,
      creditUnits,
      prerequisites: prerequisites.slice(0, 2000),
      grade: grade.slice(0, 50),
      errors,
    });
  }

  return { rows: parsed, header, inspected: rows.length };
}

export function parseCurriculumWorkbook(workbook: WorkbookInput): ParseWorkbookResult {
  const sheetScores = workbook.sheets.map(sheet => {
    const rows = applyMerges(sheet.rows, sheet.merges).map(r => cellStr(Array.isArray(r) ? r : []));
    return { sheet, rows, score: sheetHasCurriculumSignal(rows) };
  });

  const ranked = [...sheetScores].sort((a, b) => b.score - a.score);
  const selected = ranked.filter(s => s.score > 0);
  const ignored = ranked.filter(s => s.score <= 0).map(s => s.sheet.name);

  const allRows: ParsedSubjectRow[] = [];
  let rowsInspected = 0;
  let bestHeader: { sheet: string; index: number; mappings: ColumnMapping[] } | null = null;
  let bestScore = -1;

  for (const entry of selected) {
    const fallback = detectYearSemesterFromSheetName(entry.sheet.name);
    const parsed = parseSheet(entry.sheet, fallback);
    rowsInspected += parsed.inspected;
    allRows.push(...parsed.rows);
    if (parsed.header && parsed.header.score > bestScore) {
      bestScore = parsed.header.score;
      bestHeader = { sheet: entry.sheet.name, index: parsed.header.index, mappings: parsed.header.mappings };
    }
  }

  if (selected.length === 0) {
    rowsInspected = sheetScores.reduce((n, s) => n + s.rows.length, 0);
  }

  const mappings = bestHeader?.mappings ?? [];
  const missingRequired: string[] = [];
  if (!mappings.some(m => m.field === 'courseCode' && m.confidence >= 72)) missingRequired.push('Course Code');
  if (!mappings.some(m => m.field === 'descriptiveTitle')) missingRequired.push('Descriptive Title');
  if (!mappings.some(m => m.field === 'creditUnits' && m.confidence >= AUTO_HINT)) missingRequired.push('Credit Units');

  const reason = buildReason({
    sheets: workbook.sheets.length,
    selected: selected.length,
    mappings,
    missingRequired,
    subjects: allRows.length,
  });

  const diagnostic: ImportDiagnostic = {
    fileName: workbook.fileName,
    sheetsDetected: workbook.sheets.length,
    sheetNames: workbook.sheets.map(s => s.name),
    selectedSheets: selected.map(s => s.sheet.name),
    ignoredSheets: ignored,
    headerRow: bestHeader ? bestHeader.index + 1 : null,
    headerSheet: bestHeader?.sheet ?? null,
    mappedColumns: mappings.map(m => ({
      field: FIELD_LABELS[m.field],
      header: m.excelHeader,
      confidence: m.confidence,
      strength: m.strength,
    })),
    missingRequired,
    rowsInspected,
    potentialSubjectRows: allRows.length,
    reason,
    suggestedAction: allRows.length === 0
      ? (missingRequired.length ? 'Review column mapping or add clearer headers for Course Code and Descriptive Title.' : 'Check that subject rows include a course code and title, and that TOTAL/summary rows are not the only data.')
      : 'Review the detected mapping and subject list before confirming import.',
  };

  return {
    rows: allRows,
    mappings,
    diagnostic,
    lowConfidenceMappings: mappings.filter(m => m.strength === 'possible' || m.confidence < 80),
  };
}

const AUTO_HINT = 80;

function buildReason(input: {
  sheets: number;
  selected: number;
  mappings: ColumnMapping[];
  missingRequired: string[];
  subjects: number;
}): string {
  if (input.sheets === 0) return 'The workbook has no worksheets.';
  if (input.selected === 0) return 'No worksheet contained a recognizable curriculum header (Course Code + Descriptive Title).';
  if (input.subjects === 0 && input.missingRequired.includes('Course Code')) {
    return 'Course Code column could not be confidently matched.';
  }
  if (input.subjects === 0 && input.missingRequired.includes('Descriptive Title')) {
    return 'Descriptive Title column could not be confidently matched.';
  }
  if (input.subjects === 0) {
    return 'A header was detected but no rows looked like subjects (course code + title). TOTAL, notes, and empty rows are ignored.';
  }
  return 'Curriculum rows were detected from the strongest matching worksheet(s).';
}
